module.exports = {
  errorNameForTesting: 'result for testing.', // Message for testing.
  runningStopped: 'Running stopped by the user.',
  setCustomSettings1: '',
  constructorServer: 'your server does not support the "Process.hrtime" object. The utility can not be used.',
  constructorClient1: 'your browser does not support the "Window" object, or it is not a browser. The utility can not be used.',
  constructorClient2: 'your browser does not support the "Window.performance" object. Methods for testing runtime will be unavailable.',
  show1: 'Unrecognized default value. Check config: "showOutputDefault" must be a "window" or "console".',
  showArray1: 'value must be an Array.',
  showObject1: 'value must be an Object.',
  getResult1: 'unsupported type.',
  rttPoint1: 'the "rttPoint()" method: the argument must be a string.',
  rttPoint2: 'the "rttPoint()" method: the value "pointTime" must be an array.',
  rttPoint3: 'the "rttPoint()" method: the value "pointTime" must be a number.',
  rttStart1: 'the "rttStart()" method: the first argument must be a string.',
  rttStart2: 'the "rttStart()" method: the second argument must be a number.',
  rttStart3: 'the "rttStart()" method: wrong layer index.',
  rttFinish1: 'the "rttFinish()" method: the argument must be a number.',
  rttFinish2: 'the "rttFinish()" method: wrong layer index.',
  rttAverage1: 'the "rttAverage()" method: the first argument must be a function.',
  rttAverage2: 'the "rttAverage()" method: the second argument must be a number.',
  rttAverage3: 'the "rttAverage()" method: the third argument must be a string.',
  rttAverage4: 'the "rttAverage()" method: the fourth argument must be a boolean.',
  errorHandler1: 'the "errorHandler()" method: the value must be an object.',
  checkType1: 'the "checkType()" method: second argument must be a string.',
  checkType2: 'the "checkType()" method: third argument must be a string.',
  correctDecimalPlaces1: 'the "correctDecimalPlaces()" method: value must be a number.',
  wrapString1: 'value must be a string',
};
